In [ ]:
import os
from dotenv import load_dotenv

load_dotenv()
api_key = os.getenv("OPENAI_API_KEY")

API Key: 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

In [2]:
import pandas as pd

data = [
    {"issue": "AC not cooling", "solution": "Clean filter and check gas level", "category": "HVAC"},
    {"issue": "Light not working", "solution": "Replace bulb or check wiring", "category": "Electrical"},
    {"issue": "Water leakage", "solution": "Check pipe joints and valve", "category": "Plumbing"},
    {"issue": "AC making noise", "solution": "Check fan motor and clean unit", "category": "HVAC"},
]

df = pd.DataFrame(data)
df

               issue                          solution    category
0     AC not cooling  Clean filter and check gas level        HVAC
1  Light not working      Replace bulb or check wiring  Electrical
2      Water leakage       Check pipe joints and valve    Plumbing
3    AC making noise    Check fan motor and clean unit        HVAC

In [3]:
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document

# Convert data into documents
docs = []
for _, row in df.iterrows():
    text = f"Issue: {row['issue']}\nSolution: {row['solution']}\nCategory: {row['category']}"
    docs.append(Document(page_content=text))

# Create embeddings
embeddings = OpenAIEmbeddings()

# Store in FAISS
vector_db = FAISS.from_documents(docs, embeddings)

print("Vector DB created successfully!")

Vector DB created successfully!

In [4]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

def maintenance_bot(query):
    # Search similar issues
    results = vector_db.similarity_search(query, k=2)
    
    context = "\n".join([doc.page_content for doc in results])
    
    prompt = f"""
    You are a building maintenance assistant.
    
    User Issue: {query}
    
    Relevant Knowledge:
    {context}
    
    Provide:
    1. Problem category
    2. Suggested solution
    3. Priority (Low/Medium/High)
    """
    
    response = llm.invoke(prompt)
    return response.content

In [5]:
query = "AC is not cooling in room 302"
print(maintenance_bot(query))

1. Problem category: HVAC
2. Suggested solution: Clean filter and check gas level
3. Priority: High

In [6]:
import uuid
from datetime import datetime

tickets = []

def create_ticket(issue):
    ticket = {
        "ticket_id": str(uuid.uuid4())[:8],
        "issue": issue,
        "status": "Open",
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    tickets.append(ticket)
    return ticket

# Example
ticket = create_ticket("AC not cooling in Room 302")
ticket

{'ticket_id': 'd776fa59',
 'issue': 'AC not cooling in Room 302',
 'status': 'Open',
 'created_at': '2026-04-07 15:35:11'}

In [7]:
def full_maintenance_system(query):
    response = maintenance_bot(query)
    ticket = create_ticket(query)
    
    return {
        "AI_Response": response,
        "Ticket": ticket
    }

# Test
result = full_maintenance_system("Water leakage in kitchen")
result

{'AI_Response': '1. Problem category: Plumbing  \n2. Suggested solution: Check pipe joints and valve  \n3. Priority: High  ',
 'Ticket': {'ticket_id': '08997276',
  'issue': 'Water leakage in kitchen',
  'status': 'Open',
  'created_at': '2026-04-07 15:35:39'}}

In [8]:
import pandas as pd

df_tickets = pd.DataFrame(tickets)

df_tickets

  ticket_id                       issue status           created_at
0  d776fa59  AC not cooling in Room 302   Open  2026-04-07 15:35:11
1  08997276    Water leakage in kitchen   Open  2026-04-07 15:35:39